### ISSUE TITLE
generate about page

### ISSUE THREAD

**Issue by bulbil** [hello-ulises/ulises.us#10]
We talked today about a separate colophon -- to highlight the people involved and their contributions, important to ensure that our individual participation is legible. Also a place to highlight (subtly) social media outlets thought primarily ig (possibly fb?). plus any text -- maybe something about Ulises the man or quotes from his 'what is book?'

**Comment by kaylarom** [comment]
Hey! I am working on an "About" page. Still coming. In the meantime, I can't seem to edit the current about paragraph at the top of our website and I found a typo. The second Ulises mention is lowercase. Can that be fixed by us? Thanks!

**Comment by bulbil** [comment]
@kaylarom No that text is fixed (or it was presented to me as being fixed ...) I can  go ahead and change that though. Is that the only edit?

(You can actually edit that content, I would just want to show you how because it could mess up the layout.)

**Comment by bulbil** [comment]
show off the dropdown js possibility with full / excerpted text on about (and possibly for posts and all else)

**Comment by kaylarom** [comment]
Here is the text to change for the current "about" paragraph, under the address:

Ulises is a bookshop and curatorial platform dedicated to artists' books and independent art publications. Performing the model of a quarterly periodical, each curatorial season invites contributors to present publications, workshops, lectures, artworks, and collaborations in response to a theme.

**Comment by bulbil** [comment]
about page layout

hours / info
|
|___ >   - address
             - email
             - about paragraph
             - names

**Comment by bulbil** [comment]
still have some mobile testing to do but a first pass at least.
